# Pass a list of emails here. One for each person you want to notify. Or leave it blank to not send any emails.
email:
  - example_one@email.com
  - example_two@email.com

# The default interval is 600 SECONDS which is 10 minutes. You can set this to anything.
interval: 600

# This is an example of how you enter an IP address to ping
192.168.1.1:                  # This value needs to be unique so make sure it's either the IP address or URL
  type: ip                    # Excepted values are "ip" and "url"
  category: Computer          # Can be anything you want
  name: IT Computer           # Can be anything you want
  value: 192.168.1.1        # This is the IP/URL that the program will ping every 600 seconds.

# This is an example of how you enter an URL address to ping
https://google.com:           # This value needs to be unique so make sure it's either the IP address or URL
  type: url                   # Excepted values are "ip" and "url"
  category: Google            # Can be anything you want
  name: Internet              # Can be anything you want
  value: https://google.com   # This is the IP/URL that the program will ping every 600 seconds.
